### ISSUE TITLE
chaincode path

### ISSUE THREAD

**Issue by arinddas** [suddutt1/fabricnetgenerator#4]
**Solved:**
According to the logic present till 23-11-2017 
we have to create a folder structure like:
chaincode/your folder structure/chaincodename.go

**Process:**
Create the folder called "chaincode" inside fabricnetgenarator (it will be the downloaded folder name).
Now create another folder structure (your folder structure) inside "chaincode" as specified in the network-config.json file and put the chaincode in it.
chaincode/your folder structure/chaincodename.go

**Comment by suddutt1** [comment]
Updated the readme
