### ISSUE TITLE
bash cli commands mentioned in read me

### ISSUE THREAD

**Issue by arinddas** [suddutt1/fabricnetgenerator#5]
**Solved:**

Present:
docker exec -it cli bash -f ./buildandjoinchannel.sh # To build and join channel
docker exec -it cli bash -f ./chaincode id_install.sh # To install the chain code

**Corrected:**

docker exec -it cli bash -e ./buildandjoinchannel.sh # To build and join channel
docker exec -it cli bash -e ./chaincode id_install.sh # To install the chain code

**Comment by suddutt1** [comment]
Thanks for pointing out the mistake. They are updated.
